### ISSUE TITLE
python version>=3.7.x error

### ISSUE THREAD

**Issue by chlee-k** [EunjuYang/DLStreamServing#1]
https://github.com/EunjuYang/DLStreamServing/blob/91b05fb12e61ec2c03af2c7a82f2202c6d9d09a1/stream-dl-api/dlcep.py#L137

There is python-related error like below:

File "/home/ncl/anaconda3/envs/kepco/lib/python3.7/site-packages/kafka/producer/simple.py", line 54
    return '<SimpleProducer batch=%s>' % self.async

SyntaxError: invalid syntax

According to https://github.com/dpkp/kafka-python/issues/1566, we would change "kafka" package to "kafka-python" or "confluent_kafka" package.

**Comment by EunjuYang** [comment]
we tested it in python 3.6. Please check the pre-requisite.
