### ISSUE TITLE
ValueError: could not broadcast input array from shape (2) into shape (1)

### ISSUE THREAD

**Issue by chlee-k** [EunjuYang/DLStreamServing#16]
https://github.com/EunjuYang/DLStreamServing/blob/e5a538e4099bc268778cfcd3090b206538218faa/stream_dl_api/dlcep.py#L95-L112

shape 문제인것으로 보아 is_online_train일때 stream parser쪽에서 x, y ,id로 쏴주는게 
dlcep에서 y_batch에 담을 때, y만 참조해야하는데, self.buffer[0][self.lb_size:]가 y, id를 참조해서 그런거 같아요

**Comment by EunjuYang** [comment]
잉 저거 -1 붙였던것같은데 오키 확인해볼게 ㅎㅎㅎ
